# Generated by Django 2.1.5 on 2021-01-16 23:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.UUID('eff5d920-9387-442b-82bc-1a8dcccc0dd4'), editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Mentor', 'Mentor'), ('Mentee', 'Mentee')], max_length=10)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('date_of_birth', models.DateField(null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
