# Generated by Django 3.1.6 on 2021-02-09 12:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registerMentee',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('40fadd57-0f94-464e-872e-9c566d681dda'), editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=20)),
                ('State', models.CharField(default=False, max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3228ae86-6e9b-4689-b3ec-43268b5fb499'), editable=False, primary_key=True, serialize=False),
        ),
    ]
