# Generated by Django 3.1.6 on 2021-02-09 12:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210209_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('582d5342-5053-4d1e-98c6-ed841825630a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registermentee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7428ef28-4073-47d5-a6ba-cd10729c74e8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
