# Generated by Django 3.1.6 on 2021-02-09 12:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210209_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c5311634-302e-4b2b-bb37-4f98f4d204c2'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registermentee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc52788f-b746-48bd-8d86-ccd69c29c83a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
