# Generated by Django 3.1.6 on 2021-02-09 13:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210209_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='fname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='gender',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='lname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='maritalStatus',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cab4b3c5-6073-479d-8ea3-07e0e2478a9e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registermentee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('23650965-c4e5-44a5-bd3e-824a5d86129f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
