# Generated by Django 3.1.6 on 2021-02-09 13:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210209_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2b3239d0-a149-41a8-8920-88a5f3c91f64'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registermentee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0cbd6052-6283-4c4e-ba41-30fb45cdeead'), editable=False, primary_key=True, serialize=False),
        ),
    ]
