# Generated by Django 3.1.6 on 2021-02-09 13:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210209_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='age',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4dfd8905-94ce-4347-9ace-85bf28632be8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registermentee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('39c5f27c-13a8-4bb5-89a4-57b4df13f846'), editable=False, primary_key=True, serialize=False),
        ),
    ]
