# Generated by Django 3.0.4 on 2021-02-12 17:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210211_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3a1dc956-dd27-46a0-98ed-69f42684f3b9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registermentee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c751454e-7fdb-4cba-a88c-4ca66c33b276'), editable=False, primary_key=True, serialize=False),
        ),
    ]
