# Generated by Django 3.0.4 on 2021-02-12 18:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210212_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='pic',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('06915b99-04d1-4fa7-a874-8271c47de366'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registermentee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('13d8903d-7689-4d7c-90dc-6e7262fa8370'), editable=False, primary_key=True, serialize=False),
        ),
    ]
