# Generated by Django 3.0.4 on 2021-02-15 06:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210212_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ac501afc-24ef-4a31-b0e4-e4cf1d45e728'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registermentee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f6f30051-5796-4f06-8ff2-d6932ffc1585'), editable=False, primary_key=True, serialize=False),
        ),
    ]
