# Generated by Django 3.0.4 on 2021-02-15 06:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210215_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fbc663e6-d940-4ff8-9b02-163164724bff'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registermentee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1e5f7d46-cd1b-4f1e-a2dc-e664043c7756'), editable=False, primary_key=True, serialize=False),
        ),
    ]
