# Generated by Django 3.0.4 on 2021-02-15 16:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210215_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('90121b42-5443-4f9c-a8b4-240ea7c07961'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='pic',
            field=models.ImageField(null=True, upload_to='static/images/profile_pics'),
        ),
        migrations.AlterField(
            model_name='registermentee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2cf29da3-0a1c-4560-bbd1-7779b48b5334'), editable=False, primary_key=True, serialize=False),
        ),
    ]
