# Generated by Django 3.0.4 on 2021-02-15 16:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210215_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3c8584d0-0bf0-4048-9e7a-7007dd9234ee'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='pic',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='registermentee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d0335a88-5c89-4f53-a4fd-ba852febd0b4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
