# Generated by Django 3.0.4 on 2021-02-15 16:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210215_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('be28410c-55e7-438b-b9ab-5b1f22286d9b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registermentee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b498dae9-5eec-4fca-9fad-1ca2b8bf2173'), editable=False, primary_key=True, serialize=False),
        ),
    ]
