# Generated by Django 3.0.4 on 2021-02-17 15:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210217_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('58de9551-edd8-4957-a0d2-0b71267defb3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registermentee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('12bf35a2-8a51-465b-92b1-7d9e80f001d5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
