# Generated by Django 2.1.5 on 2021-01-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentee_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentee_id', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField(auto_now_add=True, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Mentee',
            },
        ),
        migrations.DeleteModel(
            name='Patient_Profile',
        ),
    ]
